
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml

modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version

loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.

license="All rights reserved"

# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]] #mandatory

# The modid of the mod

modId="fenrisrpg" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build

version="1.16.4-1.0.0" #mandatory

 # A display name for the mod
displayName="Fenris RPG" #mandatory

# A text field displayed in the mod UI
credits="Thanks to everyone who gets to read this" #optional

# A text field displayed in the mod UI
authors="FenrisFox86" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
    This Mod adds Bronze, Silver and Rubies to the game.
    You're going to need it as a core mod for my mods (that might be released one day).

    It also adds some fancy stuff for the fun.
'''